name: 🚀 Deploy to Production

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy Production
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
          DB_HOST: database
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SUPERADMIN1: ${{ secrets.SUPERADMIN1 }}
          IMAGE_BASE_URL: ${{ secrets.IMAGE_BASE_URL }}
        run: |
          docker pull thibaultyvd/meteion:production
          docker compose -p meteion-prod -f docker-compose.yml down
          docker compose -p meteion-prod -f docker-compose.yml up -d
          docker image prune -f

      - name: Run Sequelize Migrations (Production)
        run: |
          docker exec meteion npx sequelize-cli db:migrate --env production
