name: 🚀 Deploy to Staging

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy Staging
        env:
          APP_ENV: ${{ secrets.APP_ENV_STAGING }}
          DB_HOST: database
          DB_USER: ${{ secrets.STAGING_DB_USER }}
          DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
          DB_NAME: ${{ secrets.STAGING_DB_NAME }}
          TOKEN: ${{ secrets.STAGING_TOKEN }}
          CLIENT_ID: ${{ secrets.STAGING_CLIENT_ID }}
          SUPERADMIN1: ${{ secrets.SUPERADMIN1 }}
        run: |
          docker pull thibaultyvd/meteion:staging
          docker compose -p meteion-staging -f docker-compose.staging.yml down
          docker compose -p meteion-staging -f docker-compose.staging.yml up -d
          docker image prune -f

      - name: Run Sequelize Migrations (Staging)
        run: |
          docker exec meteion_staging npx sequelize-cli db:migrate --env staging
