name: 🚀 Deploy to Staging

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "docker-compose.staging.yml"
          target: "~/deployments/meteion-staging"

      - name: Deploy Staging
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: APP_ENV,DB_USER,DB_PASSWORD,DB_NAME,TOKEN,CLIENT_ID,SUPERADMIN1,IMAGE_BASE_URL
          script: |
            cd ~/deployments/meteion-staging
            docker pull thibaultyvd/meteion:staging
            docker compose -p meteion-staging -f docker-compose.staging.yml down
            docker compose -p meteion-staging -f docker-compose.staging.yml up -d
            docker image prune -f
        env:
          APP_ENV: ${{ secrets.APP_ENV_STAGING }}
          DB_USER: ${{ secrets.STAGING_DB_USER }}
          DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
          DB_NAME: ${{ secrets.STAGING_DB_NAME }}
          TOKEN: ${{ secrets.STAGING_TOKEN }}
          CLIENT_ID: ${{ secrets.STAGING_CLIENT_ID }}
          SUPERADMIN1: ${{ secrets.SUPERADMIN1 }}
          IMAGE_BASE_URL: ${{ secrets.STAGING_IMAGE_BASE_URL }}

      - name: Run Sequelize Migrations (Staging)
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker exec meteion_staging npx sequelize-cli db:migrate --env staging
